{
  config,
  lib,
  pkgs,
  inputs,
  ...
}: let
  beszelConfig = import ../data/beszel-hosts.nix;
  monitoredHosts = lib.filterAttrs (_: host:
    host.config.my-services.monitoring.beszel-agent.enable)
  inputs.self.nixosConfigurations;
  nixosSystems =
    lib.mapAttrsToList (name: host: {
      name = beszelConfig.nameOverrides.${name} or name;
      host = "${name}.${beszelConfig.tailnet}";
      port = beszelConfig.port;
      users = beszelConfig.beszelUsers;
    })
    monitoredHosts;
  externalSystems =
    lib.mapAttrsToList (name: host: {
      inherit name host;
      port = beszelConfig.port;
      users = beszelConfig.beszelUsers;
    })
    beszelConfig.externalHosts;
  systems = nixosSystems ++ externalSystems;
  configFile = (pkgs.formats.yaml {}).generate "beszel-config.yml" {inherit systems;};
in {
  options.my-services.monitoring.beszel-server.enable = lib.mkEnableOption "Beszel monitoring server";

  config = lib.mkIf config.my-services.monitoring.beszel-server.enable {
    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    assertions = [
      {
        assertion = builtins.length (lib.unique (map (s: s.name) systems)) == builtins.length systems;
        message = "Beszel system names must be unique across NixOS and external hosts";
      }
    ];

    # Containers
    virtualisation.oci-containers.containers."beszel" = {
      image = (import ../../lib/container-images.nix)."henrygd/beszel:latest";
      volumes = [
        "/home/nixos/beszel_data:/beszel_data:rw"
      ];
      ports = [
        "8090:8090/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--add-host=host.docker.internal:host-gateway"
        "--network-alias=beszel"
        "--network=beszel_default"
      ];
    };
    systemd.services."docker-beszel" = {
      restartTriggers = [configFile];
      # The YAML is authoritative. Archive the previous state before Beszel removes
      # retired systems; unchanged name/host/port tuples retain their record IDs.
      preStart = lib.mkBefore ''
        install -d -m 0755 /home/nixos/beszel_data
        if ! cmp -s ${configFile} /home/nixos/beszel_data/config.yml; then
          if [ -f /home/nixos/beszel_data/data.db ]; then
            backup=$(mktemp -d /home/nixos/beszel_data/inventory-backup-XXXXXXXX)
            for db in data.db auxiliary.db; do
              if [ -f "/home/nixos/beszel_data/$db" ]; then
                ${pkgs.sqlite}/bin/sqlite3 "/home/nixos/beszel_data/$db" ".backup '$backup/$db'"
              fi
            done
            if [ -f /home/nixos/beszel_data/config.yml ]; then
              cp /home/nixos/beszel_data/config.yml "$backup/config.yml"
            fi
          fi
          install -m 0644 ${configFile} /home/nixos/beszel_data/config.yml.new
          mv /home/nixos/beszel_data/config.yml.new /home/nixos/beszel_data/config.yml
        fi
      '';

      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-beszel_default.service"
      ];
      requires = [
        "docker-network-beszel_default.service"
      ];
      partOf = [
        "docker-compose-beszel-root.target"
      ];
      wantedBy = [
        "docker-compose-beszel-root.target"
      ];
    };

    # Networks
    systemd.services."docker-network-beszel_default" = {
      path = [pkgs.docker];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f beszel_default";
      };
      script = ''
        docker network inspect beszel_default || docker network create beszel_default
      '';
      partOf = ["docker-compose-beszel-root.target"];
      wantedBy = ["docker-compose-beszel-root.target"];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-beszel-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = ["multi-user.target"];
    };
  };
}
