{
  config,
  lib,
  pkgs,
  ...
}: let
  # Import la liste centralisée des hosts
  beszelConfig = import ../data/beszel-hosts.nix;

  # Génère la configuration YAML pour Beszel
  generateBeszelConfig = hosts: port: users: let
    # Transforme les hosts en liste de systems pour le YAML
    systemsList = lib.mapAttrsToList (name: host: {
      inherit name;
      host = host;
      port = port;
      users = users;
    }) hosts;

    # Génère le contenu YAML
    yamlContent = ''
      # Auto-generated by NixOS
      # DO NOT EDIT MANUALLY - Modify modules/configs/beszel-hosts.nix instead

      systems:
    '' + lib.concatMapStringsSep "\n" (system: ''
        - name: ${system.name}
          host: ${system.host}
          port: ${toString system.port}
          users:
      ${lib.concatMapStringsSep "\n" (user: "        - ${user}") system.users}
    '') systemsList;
  in
    pkgs.writeText "beszel-config.yml" yamlContent;

  # Génère le fichier de configuration
  configFile = generateBeszelConfig beszelConfig.hosts beszelConfig.port beszelConfig.beszelUsers;
in {
  options.my-services.monitoring.beszel-server.enable = lib.mkEnableOption "Beszel monitoring server";

  config = lib.mkIf config.my-services.monitoring.beszel-server.enable {
    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Créer le répertoire de données et copier le config généré
    system.activationScripts.beszel-setup = lib.stringAfter ["users"] ''
      mkdir -p /home/nixos/beszel_data
      cp -f ${configFile} /home/nixos/beszel_data/config.yml
      chmod 644 /home/nixos/beszel_data/config.yml
    '';

    # Containers
    virtualisation.oci-containers.containers."beszel" = {
      image = "henrygd/beszel:latest";
      volumes = [
        "/home/nixos/beszel_data:/beszel_data:rw"
      ];
      ports = [
        "8090:8090/tcp"
      ];
      log-driver = "journald";
      extraOptions = [
        "--add-host=host.docker.internal:host-gateway"
        "--network-alias=beszel"
        "--network=beszel_default"
      ];
    };
    systemd.services."docker-beszel" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-beszel_default.service"
      ];
      requires = [
        "docker-network-beszel_default.service"
      ];
      partOf = [
        "docker-compose-beszel-root.target"
      ];
      wantedBy = [
        "docker-compose-beszel-root.target"
      ];
    };

    # Networks
    systemd.services."docker-network-beszel_default" = {
      path = [pkgs.docker];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f beszel_default";
      };
      script = ''
        docker network inspect beszel_default || docker network create beszel_default
      '';
      partOf = ["docker-compose-beszel-root.target"];
      wantedBy = ["docker-compose-beszel-root.target"];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-beszel-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = ["multi-user.target"];
    };
  };
}
