# .sops.yaml

keys:
  - &primary age10yfuvwlr6su8u02sc9xmmvxj4aj59562dkxlpk0rl5kum8amw4zqaxrjpk 
  - &caddy age16w0w0ecqcjcjuzr3lthp6kgr5whz46cjvetf48xlaxdxht7yja2sdtjlyv
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age: 
        - *primary
        - *caddy
