# .sops.yaml

keys:
  - &primary age1xsuf3equ3xjmy4rsk3p8cyfalljmzpdqs2hrgrf7ceqn4efzvpzqzhgwfc 
  - &beszel 59bf8a737aa6d67d9ed8cc7707b31053a35184e0
  - &test age1sda2qzshy2fr8xplvdrqahfvnhh86lgq20rjfwjm2k2yp54nc40qmpumzl
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *primary
      - *test
    - pgp:
      - *beszel