# .sops.yaml

keys:
  - &primary age10yfuvwlr6su8u02sc9xmmvxj4aj59562dkxlpk0rl5kum8amw4zqaxrjpk 
  - &caddy age1ldjyc766hpsukvlc4hckct3ur7jvmm07rqdr3rwqq3mh67k6x4hq3awfng
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age: 
        - *primary
        - *caddy
