# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."beszel-agent" = {
    image = "henrygd/beszel-agent";
    environment = {
      "KEY" = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAC4vj5e821FKLnoBsMgHQvqOKbg7A/ACWMA8hUzQzy6";
      "PORT" = "45876";
    };
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock:ro"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=beszel-agent"
      "--network=beszel-agent_default"
    ];
  };
  systemd.services."docker-beszel-agent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-beszel-agent-root.target"
    ];
    wantedBy = [
      "docker-compose-beszel-agent-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-beszel-agent-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
