# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."beszel" = {
    image = "henrygd/beszel:latest";
    volumes = [
      "/home/tom/Documents/beszel_data:/beszel_data:rw"
    ];
    ports = [
      "8090:8090/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=beszel"
      "--network=beszel_default"
    ];
  };
  systemd.services."docker-beszel" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-beszel_default.service"
    ];
    requires = [
      "docker-network-beszel_default.service"
    ];
    partOf = [
      "docker-compose-beszel-root.target"
    ];
    wantedBy = [
      "docker-compose-beszel-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-beszel_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f beszel_default";
    };
    script = ''
      docker network inspect beszel_default || docker network create beszel_default
    '';
    partOf = [ "docker-compose-beszel-root.target" ];
    wantedBy = [ "docker-compose-beszel-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-beszel-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
