# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."calibre" = {
    image = "lscr.io/linuxserver/calibre:latest";
    environmentFiles = [
      "/home/nixos/calibre/.env"
    ];
    volumes = [
      "/home/nixos/calibre/config:/config:rw"
    ];
    ports = [
      "8080:8080/tcp"
      "8181:8181/tcp"
      "8081:8081/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=calibre"
      "--network=calibre_default"
    ];
  };
  systemd.services."docker-calibre" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-calibre_default.service"
    ];
    requires = [
      "docker-network-calibre_default.service"
    ];
    partOf = [
      "docker-compose-calibre-root.target"
    ];
    wantedBy = [
      "docker-compose-calibre-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-calibre_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f calibre_default";
    };
    script = ''
      docker network inspect calibre_default || docker network create calibre_default
    '';
    partOf = [ "docker-compose-calibre-root.target" ];
    wantedBy = [ "docker-compose-calibre-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-calibre-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
  
}
