# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."homeassistant" = {
    image = "lscr.io/linuxserver/homeassistant:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Europe/Paris";
    };
    volumes = [
      "/home/nixos/homeassistant/data:/config:rw"
    ];
    ports = [
      "8123:8123/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--device=/dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_bac3096e933aef1193792b1455516304-if00-port0:/dev/ttyUSB0"
      "--network-alias=homeassistant"
      "--network=homeassistant_default"
    ];
  };
  systemd.services."docker-homeassistant" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-homeassistant_default.service"
    ];
    requires = [
      "docker-network-homeassistant_default.service"
    ];
    partOf = [
      "docker-compose-homeassistant-root.target"
    ];
    wantedBy = [
      "docker-compose-homeassistant-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-homeassistant_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f homeassistant_default";
    };
    script = ''
      docker network inspect homeassistant_default || docker network create homeassistant_default
    '';
    partOf = [ "docker-compose-homeassistant-root.target" ];
    wantedBy = [ "docker-compose-homeassistant-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-homeassistant-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
