# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."MySpeed" = {
    image = "germannewsmaker/myspeed";
    volumes = [
      "myspeed:/myspeed/data:rw"
    ];
    ports = [
      "5216:5216/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=myspeed"
      "--network=myspeed_default"
    ];
  };
  systemd.services."docker-MySpeed" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-myspeed_default.service"
    ];
    requires = [
      "docker-network-myspeed_default.service"
    ];
    partOf = [
      "docker-compose-myspeed-root.target"
    ];
    wantedBy = [
      "docker-compose-myspeed-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-myspeed_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f myspeed_default";
    };
    script = ''
      docker network inspect myspeed_default || docker network create myspeed_default
    '';
    partOf = [ "docker-compose-myspeed-root.target" ];
    wantedBy = [ "docker-compose-myspeed-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-myspeed-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
