name: Daily NixOS Build Check

on:
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, nixos]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build daily NixOS configs (fast)
        run: |
          nix-fast-build \
            --eval-max-memory-size 10016 \
            --eval-workers 4 \
            --skip-cached \
            --no-nom
