name: NixOS CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: [self-hosted, nixos]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format check (alejandra)
        run: alejandra -c *

      - name: Build NixOS configs (fast)
        run: |
          nix-fast-build \
            --eval-max-memory-size 10016 \
            --eval-workers 6 \
            --skip-cached \
            --no-nom

      - name: Flake eval (nix-eval-jobs)
        run: nix-eval-jobs --flake .#nixosConfigurations --gc-roots-dir gcroot

      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5
        with:
          check-outdated: true
          check-owner: true
          check-supported: true
          fail-mode: true
          ignore-missing-flake-lock: false
