name: NixOS CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: [self-hosted, nixos]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Format check (alejandra)
        run: alejandra -c *

      - name: Flake eval (nix-eval-jobs)
        run: nix-eval-jobs --flake .#nixosConfigurations --gc-roots-dir gcroot



